// General-purpose Canonical Huffman decompressor for Arduino
#ifdef MOCK_ARDUINO
#include "mock_arduino.h"
#include "file_data.h"
#include <vector>
#endif

// To be defined in common.h generated by compressor
#ifndef MOCK_ARDUINO
#include "common.h"
#endif

int16_t h_num_symbols;
int16_t h_max_len;
const int16_t* h_len_counts;
const int16_t* h_sorted_symbols;

void h_setup(const int16_t* common_h) {
  h_num_symbols = pgm_read_word_near(&common_h[0]);
  h_max_len = pgm_read_word_near(&common_h[1]);
  h_len_counts = &common_h[2];
  h_sorted_symbols = &common_h[2 + h_max_len];
}

void h_decompress(const uint8_t* compressed, unsigned int original_len, unsigned long total_bits) {
    unsigned long bit_pos = 0;
    for (unsigned int i = 0; i < original_len; i++) {
        int code = 0;
        int first = 0;
        int symbol_offset = 0;

        for (int length = 1; length <= h_max_len; length++) {
            if (bit_pos >= total_bits) break;

            uint8_t b = pgm_read_byte_near(&compressed[bit_pos / 8]);
            bool bit = (b >> (7 - (bit_pos % 8))) & 1;
            bit_pos++;

            code = (code << 1) | (bit ? 1 : 0);

            int count = pgm_read_word_near(&h_len_counts[length - 1]);
            if (code < first + count) {
                int16_t symbol = pgm_read_word_near(&h_sorted_symbols[symbol_offset + (code - first)]);
                Serial.print((int)symbol);
                if (i < original_len - 1) Serial.print(",");
                goto next_symbol;
            }

            symbol_offset += count;
            first = (first + count) << 1;
        }
        next_symbol:;
    }
    Serial.println();
}

#ifdef MOCK_ARDUINO
extern "C" const int16_t common_h[];
extern std::vector<FileData> files_to_test;
void setup() {
  h_setup(common_h);
}
void loop() {
    for (auto& f : files_to_test) {
        Serial.print("File ");
        Serial.print(f.name);
        Serial.print(": ");
        h_decompress(f.data, f.len, f.bits);
    }
}
#endif
